controllers_backend:
    resource: ../../src/Controller/Backend/
    type: annotation
    prefix: /admin


controllers_frontend:
    resource: ../../src/Controller/Frontend/
    type: annotation
    prefix: /