liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
  #
  #    # define your filter sets under this option
  filter_sets:
    home_play:
      jpeg_quality:          85
      png_compression_level: 8
      filters:
        thumbnail:
          size:          [140, 140]
          mode:          inset
          allow_upscale: true
    logo_play:
      jpeg_quality:          85
      png_compression_level: 8
      filters:
        thumbnail:
          size:          [240, 75]
          mode:          inset
          allow_upscale: true
    logo_play_fav:
      jpeg_quality:          85
      png_compression_level: 8
      filters:
        thumbnail:
          size:          [120, 35]
          mode:          inset
          allow_upscale: true
    h_logo_play:
      jpeg_quality:          85
      png_compression_level: 8
      filters:
        thumbnail:
          size:          [256, 80]
          mode:          inset
          allow_upscale: true
    show_play:
      jpeg_quality:          85
      png_compression_level: 8
      filters:

        thumbnail:
          size:          [600, 140]
          mode:          outbound
          allow_upscale: true
        background:
          size:     [620, 160]
          position: center
          color:    '#222'
