version: '3.2'

services:
  jeux_database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: sf4
    volumes:
      - database:/var/lib/mysql
    container_name: jeux_database

  jeux_symfony:
    build: .
    image: registry.2le.net/joris/jeu
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html/
    ports:
      - 8921:80
    container_name: jeux_symfony
      
  jeux_pma:
    image: phpmyadmin/phpmyadmin
    links:
      - jeux_database:db
    ports:
      - 8922:80
    container_name: jeux_pma

volumes:
  database: ~
