liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
#
#    # define your filter sets under this option
    filter_sets:
#
#        # an example thumbnail transformation definition
#        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        home_play:
#
#            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
#
#            # setup the filter steps to apply for this transformation
            filters:
#
#                # auto rotate the image using EXIF metadata
#                auto_rotate: ~
#
#                # strip the image of all metadata
#                strip: ~
#
#                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [140, 140]
                    mode:          inset
                    allow_upscale: true
        logo_play:
#
#            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
#
#            # setup the filter steps to apply for this transformation
            filters:
#
#                # auto rotate the image using EXIF metadata
#                auto_rotate: ~
#
#                # strip the image of all metadata
#                strip: ~
#
#                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [240, 75]
                    mode:          inset
                    allow_upscale: true
        h_logo_play:
#
#            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
#
#            # setup the filter steps to apply for this transformation
            filters:
#
#                # auto rotate the image using EXIF metadata
#                auto_rotate: ~
#
#                # strip the image of all metadata
#                strip: ~
#
#                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [256, 80]
                    mode:          inset
                    allow_upscale: true
        show_play:
            jpeg_quality:          85
            png_compression_level: 8
            filters:

                thumbnail:
                    size:          [600, 140]
                    mode:          outbound
                    allow_upscale: true
#                # create border by placing image on larger black background
                background:
                    size:     [620, 160]
                    position: center
                    color:    '#222'
